---
title: "distributed-sudoku-solver-analysis"
output: html_document
---

# Three strategies recursions comparison

```{r}
x <- c(1,3,5,8,11)
mosty <- c(8.51034,1.60018,0.41041,0.00927,0.00122)
leasty <- c(17.06548, 2.11849, 0.43952, 0.01215, 0.00374)
defaulty <- c(10.15919,1.67568,0.4144,0.00964,0.00155)

plot(x,mosty,col='red', type="l",ylab = "num of recursions", xlab = "num of prop. rounds")
points(x,leasty,col='green', type="l")
points(x,defaulty,col='blue', type="l")
legend("topright", legend=c("MOST", "LEAST","DEFAULT"),col=c("red","green", "blue"), lty=1:2, cex=0.8)
```


# Three strategies propagations comparison

```{r}
x <- c(1,3,5,8,11)
mosty <- c(9.51034,7.80054,7.05205,8.07416,11.01342)
leasty <- c(18.06548,9.35547,7.1976,8.0972,11.04114)
defaulty <- c(11.15919,8.02704,7.072,8.07712,11.01705)

plot(x,mosty,col='red', type="l",ylab = "num of propagations", xlab = "num of prop. rounds")
points(x,leasty,col='green', type="l")
points(x,defaulty,col='blue', type="l")
legend("top", legend=c("MOST", "LEAST","DEFAULT"),col=c("red","green", "blue"), lty=1:2, cex=0.8)
```



